spring:
  application:
    name: StudyMate
  datasource:
    url: jdbc:mysql://localhost:3307/studymeet
    username: studymeet
    password: 12345
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: true
security:
  jwt:
    secret_key: 4eeab38d706831be4b36612ead768ef8182d1dd6f0e14e5dc934652e297fb16a
    access_token_expiration: 36000000 # 10 hours
    refresh_token_expiration: 252000000 # 7 days
logging:
  file:
    name: logs.log
socket:
  host: 127.0.0.1
  port: 8081